// @flow
export const FETCH_REQUEST: string = 'HOME_COMPONENT/FETCH_REQUEST';
export const FETCH_SUCCESS: string = 'HOME_COMPONENT/FETCH_SUCCESS';
export const FETCH_FAILURE: string = 'HOME_COMPONENT/FETCH_FAILURE';
export const FETCH_CANCEL: string = 'HOME_COMPONENT/FETCH_CANCEL';

export const RESET: string = 'HOME_COMPONENT/RESET';
